### PR TITLE
Feature/protocol 3

### PR DESCRIPTION
**Pull request by anaumov**
Made changes to implement spec for protocol v3 https://github.com/logux/logux-rack/issues/9.

@ai I need your help with this. I read the [request on cultofmartians](https://cultofmartians.com/tasks/logux-rack-backend3.html) and [the review on former PR](https://github.com/logux/logux-rack/pull/10). Here are my questions:

1. I removed the stream and replace it with the plain response because it's not possible to return 500 if the stream already started. Is this ok?
2. I found only one case when it has to return 500. It's when we process `verify_request_meta_data`, rest of the things will be rescued. Am I correct?
3. You mentioned that logux backend protocol has no answer `unauthorized` https://github.com/logux/logux-rack/pull/10. What should happen when the secret does not match?

### CODE REVIEW

**Comment by ai** [comment]
> I removed the stream and replace it with the plain response because it's not possible to return 500 if the stream already started. Is this ok?

Nope, streams are very important for performance on bunch requests.

> I found only one case when it has to return 500. It's when we process verify_request_meta_data, rest of the things will be rescued. Am I correct?

Nope. You never send 500.

> You mentioned that logux backend protocol has no answer unauthorized #10. What should happen when the secret does not match?

`403` with `Wrong secret` in the body.

Here is a tool to test Logux implementation. You can use it as a protocol reference https://github.com/logux/backend-test/blob/master/tests/protocol.js

**Comment by anaumov** [comment]
@ai thanks for your reply!

> Nope, streams are very important for performance on bunch requests.

I return the stream to the project.

> Here is a tool to test Logux implementation. You can use it as a protocol reference https://github.com/logux/backend-test/blob/master/tests/protocol.js

Cool! I've added error handling for wrong secret, wrong protocol, and wrong request body.

Please, review PR again.

**Comment by ai** [comment]
@anaumov it looks good, but I have no time to review it properly (sorry, the really hard moment in PostCSS).

The best way to check implementation will be not a review, but using [`@logux/backend-test`](https://github.com/logux/backend-test). If you have time and motivation it will be better to add this test system here (I made a step-by-step guide there).

**Comment by anaumov** [comment]
@ai ок, thanks! Will test it and get back to you.

**Comment by anaumov** [comment]
@ai I'm back and I need your attention)

@logux/beckend-test was designed to test protocol 4 and I forced to tune it to be able to test protocol 3. I tested only: body validation, secret, and protocol version. For testing actual messages I have to rewrite tests. I'm not sure that's good idea, because it'll be better to spend time on protocol 4 here. Here it is my changes for testing https://github.com/anaumov/backend-test/commit/57a6216f8191bf88233fdf67417f7e1838dcdedb and video with testing https://www.loom.com/share/117d79a68c744a679de520ac51e20db7

I cleaned up the code a little bit and make it green. Let me know what do you think.

**Comment by ai** [comment]
Great. Let’s start from Backend Protocol 3 and will `@logux/beckend-test` when we will migrate to the protocol 4

**Comment by ai** [comment]
@dreikanter we are ready to merge

**Comment by anaumov** [comment]
@ai @dreikanter guys, how can help you to speed up the process of merging request?

**Comment by ai** [comment]
@anaumov I pinged him @dreikanter

**Comment by dreikanter** [comment]
Hi @anaumov! Thank you for your great contribution! I'm sorry for the delay, I'm on vacation at the moment.

**Pull request merged**
